use uncaught exception handler

process.on('   uncaughtException', function(err){
	console.error(err);
	process.exit(1); // we exit manually
});
